### ISSUE TITLE
Missing PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by goapunk** [n8fr8/tor-android#6]
I just saw that `PKG_CONFIG_PATH="$(EXTERNAL_ROOT)/lib/pkgconfig"` is missing in the call to Tor's configure for lzma and zstd to be picked up, looks like I forgot that, sorry! Apart form that Tor browser doesn't seem to use lzma or zstd, so maybe we just follow their example and remove it for now. Thish might make it easier to compile it against the latest NDK as well.

**Comment by n8fr8** [comment]
Sorry, but what is the actual problem you are seeing? We are compiling lzma and zstd, but you think the tor compile is not including those? 

Also, is there problem compiling those with the latest NDK? I haven't tried upgrading yet on my system, though likely we should keep current.

**Comment by goapunk** [comment]
>Sorry, but what is the actual problem you are seeing? We are compiling lzma and zstd, but you think the tor compile is not including those?

Yes, we are building them but they aren't linked into Tor.

>Also, is there problem compiling those with the latest NDK? I haven't tried upgrading yet on my system, though likely we should keep current.

The latest NDK which works without modifying is 15(b), from 16 on the ndk only comes with the unified headers which (from what I recall last time I tested it) requires some modification of the Makefile (I couldn't make it work for lzma/zstd).

**Comment by n8fr8** [comment]
We specifically added those new compression libraries in when tor added them a few releases ago. Without them, tor wouldn't compile, so there is some configured dependency somewhere. 

Ideally, compression is helpful in a mobile data environment, so it would be great to be able to have it working.

**Comment by goapunk** [comment]
>We specifically added those new compression libraries in when tor added them a few releases ago. Without them, tor wouldn't compile, so there is some configured dependency somewhere.

well, apparently it did :)

>Ideally, compression is helpful in a mobile data environment, so it would be great to be able to have it working.

I agree, although compression means higher battery use, so it's a trade-off. If you want to keep it adding `PKG_CONFIG_PATH="$(EXTERNAL_ROOT)/lib/pkgconfig"` in line 257 should be enough to have it linked in.

**Comment by grote** [comment]
Has this been fixed by 93663355fa87bf2313aaa706944c6d3dd28a81ed ?

**Comment by goapunk** [comment]
Yup:
> Tor 0.3.4.8 (git-da95b91355248ad8) running on Linux with Libevent 2.0.22-stable, OpenSSL 1.0.2p, Zlib 1.2.8, Liblzma 5.2.3, and Libzstd 1.3.2.
