### ISSUE TITLE
Use --disable-module-dirauth to exclude the code for directory authorities

### ISSUE THREAD

**Issue by grote** [n8fr8/tor-android#7]
Would be great if we could use the new `--disable-module-dirauth` option when building to exclude the code for directory authorities making the binary somewhat smaller.

**Comment by n8fr8** [comment]
Yes, talked about this at the Tor dev meeting. Adding it now!

**Comment by n8fr8** [comment]
(sadly it doesn't seem to have much impact on binary size)
